# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f57bf427740320832a31a2d337351ab7ddb64a2d741bbfbeebb0ffe0edd2da5b56dc32ae948cc8b99b60837924f2aeffb3868de0803afe4af53d14d2d3d66ea

test:
  secret_key_base: 93ba7235aec2b6827a28d100696c8e1a05c939c6ccdbc7f96e62f53a4debff9dcb449ef3312f9dd7b9a8187f407fe1526e8075ad71eecced8e2bc1f086a42a6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
